version: "4"
services:
    mi_app:
      build: .
      ports:
        - "3000:3000"

      links:
        - postgres

      volumes:
        postgres-data:/var/lib/postgresql/data

    postgres:
     image: postgres:17.9
     ports: "5432:5432"

volumes:
  postgres-data:
