events {}

http {
    upstream auth {
        server auth-service:3000;
    }
    upstream agenda {
        server agenda-service:3001;
    }
    upstream inscription {
        server inscription-service:3002;
    }
    upstream notification {
        server notification-service:4000;
    }

    server {
        listen 80;
        server_name _;

        location /api/auth/ {
            proxy_pass http://auth/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        location /api/agenda/ {
            proxy_pass http://agenda/;
            proxy_set_header Host $host;
        }
        location /api/inscription/ {
            proxy_pass http://inscription/;
            proxy_set_header Host $host;
        }
        location /api/notification/ {
            proxy_pass http://notification/;
            proxy_set_header Host $host;
        }
    }
}
