name: Pipeline CONIITI

on:
  push:
    branches: [main]

jobs:
  construir-y-probar:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Clonar el codigo
        uses: actions/checkout@v4

      - name: 2. Configurar Node.js
        uses: actions/setup-node@v4
        
        with:
          node-version: 18
      
      - name: 3. Isntalar dependencias de node
        run: npm install

  run-lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      