name: Pipeline CONIITI

on:
  push:
    branches: [main]

jobs:
  construir-y-desplegar:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Clonar el código
        uses: actions/checkout@v4

      - name: 2. Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: 3. Instalar dependencias
        run: npm install

      - name: 4. Construir el proyecto (Build)
        # Esto genera la carpeta 'dist' o 'build' necesaria para producción
        run: npm run build --workspaces --if-present

      - name: 5. Desplegar en Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          # Nombre exacto del App Service en Azure
          app-name: 'coniiti' 
          # Este perfil lo descargas desde el portal de Azure (Get Publish Profile)
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
