name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "desarrollo-rediseño-david", "desarrollo-diseño" ]
  pull_request:
    branches: [ "main" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build_test_lint:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./frontend/vite-project

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Instalar dependencias
      run: npm ci

    - name: Linting
      run: npm run lint || true

    - name: Pruebas Unitarias
      run: npm run test || true

    - name: Build Estricto
      run: CI=true npm run build
